name: Slack Message
description: Send messages to Slack from GitHub Actions.
branding:
  icon: message-square
  color: purple
runs:
  using: node12
  main: ./index.dist.js
inputs:
  text:
    description: Text to send to Slack, in Slack's "mrkdwn" format - required.
    required: true
  color:
    description: The colour of the Slack attachment.
    required: false
  bot-token:
    description: A Slack bot token to send messages with - required if `webhook-url` was not provided.
    required: false
  webhook-url:
    description: A Slack webhook URL to send messages to - required if `bot-token` was not provided.
    required: false
  channel:
    description: The Slack channel - required if `bot-token` was provided.
    required: false
  message-id:
    description: The ID of the existing Slack message to update - only valid if `bot-token` was provided.
    required: false
outputs:
  message-id:
    description: The unique identifier of the Slack message sent.
